config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  root to: "home#index"
  devise_for :users
  resources :books
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates_presence_of :name
  validates_presence_of :author
  validates_presence_of :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :correct_user, except: [:index]

  # GET /books or /books.json
  def index
    @books = current_user.books
  end

  # GET /books/1 or /books/1.json
  def show; end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit; end

  # POST /books or /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @book = current_user.books.find_by(id: params[:id])
    redirect_to books_path if @book.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:name, :author, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? 'nav-link active' : 'nav-link'
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">

  <h1><%= book.name %></h1>
  <h4><%= book.author %></h4>
  
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-2">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name, class:"form-control border-dark-subtle bg-body-tertiary" %>
  </div>

  <div class="my-2">
    <%= form.label :author, class:"form-label" %>
    <%= form.text_field :author, class:"form-control border-dark-subtle bg-body-tertiary" %>
  </div>

  <div class="my-2">
    <%= form.number_field :user_id, id: :book_user_id, type: :hidden, value:current_user.id, class:"form-control border-dark-subtle bg-body-tertiary" %>
  </div>


  <div>
    <%= form.submit class:"btn btn-primary my-2"%>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container bg-secondary-subtle px-5 py-3 rounded-4 shadow">
  <h1>Editing book</h1>

  <%= render "form", book: @book %>

  <div class="my-2">
    <%= link_to "Show this book", @book, class:"btn btn-secondary" %> 
    <%= link_to "Back to books", books_path, class:"btn btn-secondary" %>
  </div>
</div>

app/views/books/index.html.erb
<h1>Books</h1>
<%= link_to "New book", new_book_path, class:"btn btn-secondary mb-3" %>


<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
      <th scope="row"><%= book.id %></th>
      <td><%= book.name %></td>
      <td><%= book.author %></td>
      <td><%= link_to "Edit", edit_book_path(book) %></td>
      <td><%= link_to "Show", book %></td>
      <td><%= link_to "Delete", book, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<div class="container bg-secondary-subtle px-5 py-3 rounded-4 shadow">
  <h1>New book</h1>

  <%= render "form", book: @book %>

  <div>
    <%= link_to "Back to books", books_path, class:"btn btn-secondary my-2" %>
  </div>
</div>

app/views/books/show.html.erb
<div class="container bg-secondary-subtle px-5 py-3 rounded-4 shadow">
<%= render @book %>
  <%= link_to "Edit", edit_book_path(@book), class:"btn btn-secondary my-3"%> 
  <%= link_to "Back", books_path, class:"btn btn-secondary my-3"%>

  <%= button_to "Delete book", @book, method: :delete, class:"btn btn-danger mb-3" %>
</div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'Bookrrow', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Home', root_path, class: active_class(root_path) %>
          </li>

          <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to 'Books', books_path, class: active_class(books_path) %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: active_class(edit_user_registration_path) %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log Out', destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link"%>
          </li>

          <% else %>

          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: active_class(new_user_registration_path) %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class: active_class(new_user_session_path) %>
          </li>

          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>ABOUT.....</h1>

app/views/home/index.html.erb
<h1>Welcome to Bookrrow!</h1>
<% if user_signed_in?%>
  <p>Go to <%= link_to 'Books', books_path %> to check your books!</p>
<% else %>
  <p>Please log in to manage your books!</p>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show mt-3" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bookrrow</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render "home/navbar" %>

    <div class="container my-4">

      <% if notice %>
        <%= render "layouts/alerts" %>
      <% end %>

      <%= yield %>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>